spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/sonetrack
    username: postgres
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: task-thread-

converter:
  url:
    track-url: http://192.168.1.132:8082/get-new-requests
  queries:
    - магазин магнит просрочка
    - магнит тухлятина

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  address: 192.168.1.132
  port: 8081

scheduler:
  fetch-new-request:
    fixed-rate-in-ms: 600000
  ignore-request:
    fixed-rate-in-ms: 86400000
    age-period: P1W

