spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-228-207-163.eu-west-1.compute.amazonaws.com:5432/d3sl39uedsu61q
    username: mnzglfvlallppm
    password: f59ff196fe1e6531413942a8b46493c37aae594dbb7fe6ef81e382b02624b417

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: task-thread-

converter:
  url:
    track-url: http://track-converter.herokuapp.com/get-new-requests
  queries:
    - магазин магнит просрочка
    - магнит тухлятина
    - магазин магнит
    - просроченные товары
    - магнит хамство

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

scheduler:
  fetch-new-request:
    fixed-rate-in-ms: 600000
  ignore-request:
    fixed-rate-in-ms: 86400000
    age-period: P1W

